cmd/testbot: update testbot for new api
Testbot now runs our 5 minute guide program. You can run the
tests locally (inside a docker container) by running `sh bin/run-tests`.
After this PR lands It will be deployed onto an ec2 instance and listen
for commits to `main` through a GH webhook. These commits will
trigger the tests to be run and the results will be reported to a
dedicated
slack channel.

Future work involves automating the build & deploy process and adding
a dedicated slash command for slack.

Closes chain/chainprv#1660
Reviewers: @kr

diff --git a/bin/run-tests b/bin/run-tests
--- a/bin/run-tests
+++ b/bin/run-tests
@@ -1,36 +1,14 @@
 #!/bin/sh
 set -xue
 
-# Disable cgo entirely.
-# We have seen one too many problems with cgo,
-# including an occasional (rare) malloc failure.
-# See https://github.com/lib/pq/issues/395.
-export CGO_ENABLED=0
-
-tag=`git describe --tags`
-commit=`git rev-parse HEAD`
-date=`date +%s`
-ldflags="-X main.buildTag=$tag -X main.buildCommit=$commit -X main.buildDate=$date"
-
-cleanup() {
-  rm -f $CHAIN/docker/testbot/cored
-  rm -f $CHAIN/docker/testbot/corectl
-  rm -f $CHAIN/docker/testbot/schema.sql
-}
+# The function body is wrapped in a subshell so that
+# failure of the "docker rmi" command doesn't trigger
+# a test failure (due to set -e)
+cleanup() {(
+  set +e
+  docker rmi `docker images -f "dangling=true" -q`
+)}
 trap "cleanup" EXIT
 
-GOOS=linux GOARCH=amd64 go build\
-  -tags 'insecure_disable_https_redirect'\
-  -ldflags "$ldflags"\
-  -o $CHAIN/docker/testbot/cored\
-  chain/cmd/cored
-
-GOOS=linux GOARCH=amd64 go build\
-  -o $CHAIN/docker/testbot/corectl\
-  chain/cmd/corectl
-
-cp $CHAIN/core/schema.sql $CHAIN/docker/testbot/schema.sql
-
 docker build --tag testbot $CHAIN/docker/testbot/
-docker run --rm --name testbot -e PRIV1=$PRIV1 -e PRIV2=$PRIV2 -e PUB1=$PUB1 -e PUB2=$PUB2 testbot
-docker rmi `docker images -f "dangling=true" -q`
+docker run --rm -v $CHAIN:/go/src/chain --name testbot testbot
